# Stubs for rdflib.plugins.serializers.nt (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rdflib.serializer import Serializer
from typing import Any, Optional

class NTSerializer(Serializer):
    encoding: str = ...
    def __init__(self, store: Any) -> None: ...
    def serialize(self, stream: Any, base: Optional[Any] = ..., encoding: Optional[Any] = ..., **args: Any) -> None: ...

class NT11Serializer(NTSerializer):
    def __init__(self, store: Any) -> None: ...

_quoteLiteral: Any
