# Stubs for scales.tornadohandler (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import tornado.web
from greplin.scales import tornadolike

class StatsHandler(tornadolike.Handler, tornado.web.RequestHandler): ...
