# Stubs for twisted.python (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .compat import unicode
from .deprecate import deprecatedModuleAttribute
from .versions import Version
from typing import Any

log: Any
