# Stubs for twisted.python.win32 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

ERROR_FILE_NOT_FOUND: int
ERROR_PATH_NOT_FOUND: int
ERROR_INVALID_NAME: int
ERROR_DIRECTORY: int
O_BINARY: Any
