# Stubs for autobahn.websocket (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from autobahn.websocket.interfaces import IWebSocketChannel as IWebSocketChannel
from autobahn.websocket.types import ConnectionAccept as ConnectionAccept, ConnectionDeny as ConnectionDeny, ConnectionRequest as ConnectionRequest, ConnectionResponse as ConnectionResponse, IncomingMessage as IncomingMessage, Message as Message, OutgoingMessage as OutgoingMessage
