# Stubs for autobahn.websocket.util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def create_url(hostname: Any, port: Optional[Any] = ..., isSecure: bool = ..., path: Optional[Any] = ..., params: Optional[Any] = ...): ...
def parse_url(url: Any): ...
